name:  QualityOps Docker CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t ai-qualityops-framework .

    - name: Run Playwright Tests inside Docker
      run: docker run --rm ai-qualityops-framework